// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.DataAccess.Data;

#nullable disable

namespace MovieApp.DataAccess.Data.Migrations
{
    [DbContext(typeof(MovieAppDbContext))]
    [Migration("20260117123445_mig_2")]
    partial class mig_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieApp.DataAccess.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Directors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Hollywood Blvd, Los Angeles, CA",
                            Age = 74,
                            City = "Los Angeles",
                            Description = "An American filmmaker known for his work in the adventure and science fiction genres.",
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Sunset St, Los Angeles, CA",
                            Age = 50,
                            City = "Los Angeles",
                            Description = "A British-American filmmaker known for his complex storytelling and innovative techniques.",
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Vine St, Los Angeles, CA",
                            Age = 58,
                            City = "Los Angeles",
                            Description = "An American filmmaker known for his stylized violence and sharp dialogue.",
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Hollywood Blvd, New York, NY",
                            Age = 78,
                            City = "New York",
                            Description = "An American filmmaker known for his work on crime films and character studies.",
                            Name = "Martin Scorsese"
                        });
                });

            modelBuilder.Entity("MovieApp.DataAccess.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("Imdb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
