// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.DataAccess.Data;

#nullable disable

namespace MovieApp.DataAccess.Data.Migrations
{
    [DbContext(typeof(MovieAppDbContext))]
    partial class MovieAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieApp.DataAccess.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Directors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Hollywood Blvd, Los Angeles, CA",
                            Age = 74,
                            City = "Los Angeles",
                            Description = "An American filmmaker known for his work in the adventure and science fiction genres.",
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Sunset St, Los Angeles, CA",
                            Age = 50,
                            City = "Los Angeles",
                            Description = "A British-American filmmaker known for his complex storytelling and innovative techniques.",
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Vine St, Los Angeles, CA",
                            Age = 58,
                            City = "Los Angeles",
                            Description = "An American filmmaker known for his stylized violence and sharp dialogue.",
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Hollywood Blvd, New York, NY",
                            Age = 78,
                            City = "New York",
                            Description = "An American filmmaker known for his work on crime films and character studies.",
                            Name = "Martin Scorsese"
                        });
                });

            modelBuilder.Entity("MovieApp.DataAccess.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("Imdb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A thief who steals corporate secrets ",
                            DirectorId = 1,
                            Duration = 148,
                            Imdb = 8.8m,
                            ReleaseYear = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Description = "When the menace known as the Joker wreaks havoc",
                            DirectorId = 1,
                            Duration = 152,
                            Imdb = 9.0m,
                            ReleaseYear = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The lives of two mob hitmen intertwine.",
                            DirectorId = 2,
                            Duration = 154,
                            Imdb = 8.9m,
                            ReleaseYear = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Description = "With the help of rescue.",
                            DirectorId = 2,
                            Duration = 165,
                            Imdb = 8.4m,
                            ReleaseYear = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Django Unchained"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A writer encounters serving",
                            DirectorId = 3,
                            Duration = 99,
                            Imdb = 8.1m,
                            ReleaseYear = new DateTime(2014, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Grand Budapest Hotel"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A pair of young lovers flee to find them.",
                            DirectorId = 3,
                            Duration = 94,
                            Imdb = 7.8m,
                            ReleaseYear = new DateTime(2012, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Moonrise Kingdom"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Two imprisoned",
                            DirectorId = 4,
                            Duration = 142,
                            Imdb = 9.3m,
                            ReleaseYear = new DateTime(1994, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        });
                });

            modelBuilder.Entity("MovieApp.DataAccess.Models.Movie", b =>
                {
                    b.HasOne("MovieApp.DataAccess.Models.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("MovieApp.DataAccess.Models.Director", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
